declare module "*.jpg";
declare module "*.gif";
declare module "*.png";

// "@types/lodash": "^4.14.168",
// "@typescript-eslint/eslint-plugin": "^4.22.1",
// "@typescript-eslint/parser": "^4.22.1",
// "copy-webpack-plugin": "^8.1.1",
// "css-loader": "^5.2.6",
// "eslint": "^7.2.0",
// "eslint-config-airbnb-base": "^14.2.1",
// "eslint-plugin-import": "^2.22.1",
// "extract-text-webpack-plugin": "^3.0.2",
// "file-loader": "^6.2.0",
// "html-webpack-plugin": "^5.3.2",
// "sass": "^1.35.1",
// "sass-loader": "^7.3.1",
// "style-loader": "^2.0.0",
// "ts-loader": "^9.2.3",
// "typescript": "^4.3.4",
// "url-loader": "^4.1.1",
// "webpack-cli": "^4.7.2",
// "webpack-dev-server": "^3.11.2"
